### ISSUE TITLE
can you make one of these for ElasticSearch?

### ISSUE THREAD

**Issue by diwu1989** [gcollazo/mongodbapp#9]
Would love to be able to have a Elasticsearch.app as well

**Comment by gcollazo** [comment]
Hi. I made this app because I have a need for it and decided to share it. I don't have a need for elastic search version right now, so I can't spend the time building it.

I encourage you to clone the app and made an elastic search version just like @jpadilla did with https://github.com/jpadilla/redisapp. It should be easy enough.
